kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: jbl2024/latelier
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    auto_tag: true
    tags: 
      - latest
      - '2.9.1'

trigger:
  ref:
  - refs/heads/master
  - refs/tags/*
