kind: pipeline
name: default

steps:
- name: docker  
  image: plugins/docker
  settings:
    repo: jbl2024/latelier
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest
      - ${DRONE_TAG}
    auto_tag: true
    force_tag: true

trigger:
  ref:
  - refs/tags/*
